platform :ios, '9.0'
target "skZone" do
    pod 'AFNetworking', '~> 3.2.0'
    pod 'SDWebImage'
    pod 'IQKeyboardManager', '~> 6.2.0'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'MJRefresh', '~> 3.1.15.7'
    pod 'MJExtension'
    pod 'SVProgressHUD'
    pod 'YYKit'
    pod 'ZFPlayer', '~> 3.0'
    pod 'ZFPlayer/ControlView', '~> 3.0'
    pod 'ZFPlayer/AVPlayer', '~> 3.0'
    pod 'KTVHTTPCache'
    pod 'TZImagePickerController'
#    pod 'MLeaksFinder'
#    pod 'YBImageBrowser'
    pod 'CTool', '~> 1.1.1'
    pod 'Masonry'
    pod 'Bugly'
  

end













